#This is where boys become men
#Where kids cry and mothers are unaware
#This is my undoing. There was nothing else I could do, I was mildly inconvenienced!

def spellchooser(P1, spelllvl = 10, spelllist = 'none', spellname = 'none', qtd = 1, stat = 'none', source = 'Class'):
  
  SpellList  = {'Cleric': ['Aid', 'Bane', 'Bless', 'Blindness/Deafness', 'Calm Emotions', 'Cure Wounds', 'Enhance Ability', 'Guiding Bolt', 'Healing Word', 'Hold Person', 'Inflict Wounds', 'Sanctuary', 'Sacred Flame', 'Shield of Faith', 'Silence', 'Spiritual Weapon', 'Toll the Dead', 'Word of Radiance'], 'Sorcerer': ['Absorb Elements', 'Acid Splash', 'Agnazzar\'s Scorcher', 'Blade Ward', 'Blindness/Deafness', 'Blur', 'Booming Blade', 'Burning Hands', 'Catapult', 'Charm Person', 'Chill Touch', 'Chromatic Orb', 'Cloud of Daggers', 'Color Spray', 'Crown of Madness', 'Dragon\'s Breath', 'Dust Devil', 'Earth Tremor', 'Enhance Ability', 'Enlarge/Reduce', 'Expeditious Retreat', 'False Life', 'Fire Bolt', 'Flaming Sphere', 'Frostbite', 'Grease', 'Green-Flame Blade', 'Gust of Wind', 'Hold Person', 'Ice Knife', 'Infestation', 'Invisibility', 'Lightning Lure', 'Mage Armor', 'Magic Missile', 'Magic Weapon', 'Mind Sliver', 'Mind Spike', 'Mirror Image', 'Misty Step', 'Phantasmal Force', 'Poison Spray', 'Ray of Frost', 'Ray of Sickness', 'Rime\'s Binding Ice', 'Scorching Ray', 'Shadow Blade', 'Shatter', 'Shield', 'Silvery Barbs', 'Sleep', 'Snilloc\'s Snowball Swarm', 'Tasha\'s Caustic Brew', 'Tasha\'s Mind Whip', 'Thunderclap', 'Thunderwave', 'Witch Bolt']}
  SpellLvl = {0: ['Acid Splash', 'Blade Ward', 'Booming Blade', 'Chill Touch', 'Fire Bolt', 'Frostbite', 'Green-Flame Blade', 'Infestation', 'Lightning Lure', 'Mind Sliver', 'Poison Spray', 'Ray of Frost', 'Sacred Flame', 'Spare the Dying', 'Thunderclap'], 1:['Absorb Elements', 'Bane', 'Bless', 'Burning Hands', 'Catapult', 'Charm Person', 'Chromatic Orb', 'Color Spray', 'Cure Wounds', 'Earth Tremor', 'Expeditious Retreat', 'False Life', 'Guiding Bolt', 'Healing Word', 'Ice Knife', 'Inflict Wounds', 'Mage Armor', 'Magic Missile', 'Ray of Sickness', 'Shield', 'Shield of Faith', 'Sleep', 'Tasha\'s Caustic Brew', 'Thunderwave', 'Witch Bolt'], 2:['Agnazzar\'s Scorcher', 'Aid', 'Blindness/Deafness', 'Blur', 'Booming Blade', 'Calm Emotions', 'Cloud of Daggers',  'Crown of Madness', 'Dragon\'s Breath', 'Dust Devil',  'Enhance Ability', 'Enlarge/Reduce', 'Flaming Sphere', 'Grease', 'Gust of Wind', 'Hold Person', 'Invisibility',  'Magic Weapon', 'Mind Spike', 'Mirror Image', 'Misty Step', 'Phantasmal Force', 'Rime\'s Binding Ice',  'Sanctuary', 'Scorching Ray', 'Shadow Blade', 'Shatter', 'Silence', 'Silvery Barbs', 'Snilloc\'s Snowball Swarm', 'Spiritual Weapon', 'Tasha\'s Mind Whip']}

  SpellList = SpellLvl
  pass
